//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.ciudadcliente = new HashSet<ciudadcliente>();
            this.cliente_telefono = new HashSet<cliente_telefono>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string direccion { get; set; }
        public Nullable<int> id_catalogo { get; set; }
        public Nullable<int> id_catalogo_dos { get; set; }
        public Nullable<int> id_catalogo_tres { get; set; }
        public int id_catalogo_cinco { get; set; }
    
        public virtual catalogo catalogo { get; set; }
        public virtual catalogo catalogo1 { get; set; }
        public virtual catalogo catalogo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ciudadcliente> ciudadcliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_telefono> cliente_telefono { get; set; }
        public virtual catalogo catalogo3 { get; set; }
    }
}
